import XCTest
@testable import StickyCastCore

/// Cross-component round trip: read fixtures/roundtrip.json (machine-generated by the extension
/// encoder) as-is, and check that the real app parser restores each encoded value back to its
/// original input. Matching test on the extension side: extension/test/crosscomponent.test.ts
/// (verifies the same file through the encoder). Since both components share one machine-generated
/// source, there is no risk of both passing the same hand-typed wrong vector.
final class CrossComponentTests: XCTestCase {
    private struct Fixture: Decodable { let input: String; let encoded: String; let note: String? }
    private struct Root: Decodable { let fixtures: [Fixture] }

    private func loadFixtures() throws -> [Fixture] {
        // Locate the shared fixtures at the repo root relative to this source file
        // (independent of cwd or build directory).
        // .../app/Tests/StickyCastTests/CrossComponentTests.swift → 4 levels up = repo root
        var root = URL(fileURLWithPath: #filePath)
        for _ in 0..<4 { root.deleteLastPathComponent() }
        let url = root.appendingPathComponent("fixtures/roundtrip.json")
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Root.self, from: data).fixtures
    }

    func testFixturesRoundTripThroughParser() throws {
        let fixtures = try loadFixtures()
        XCTAssertFalse(fixtures.isEmpty, "픽스처 로드 실패/빈 배열 — 경로 회귀 가드")

        for fx in fixtures {
            let url = try XCTUnwrap(
                URL(string: "sticky://new?content=\(fx.encoded)"),
                "URL 생성 실패: \(fx.encoded)")
            let result = StickyURLParser.parse(url)
            XCTAssertEqual(
                result, .success(fx.input),
                "파서가 원문을 복원하지 못함 (\(fx.note ?? fx.input)) — encoded=\(fx.encoded)")
        }
    }
}
